const obj = {
  people: [
    {
      firstName: "Anibal",
      lastName: "Botsford",
      job: { team: "technologies", title: "24/7", workplace: "Howe Group" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "LeemaPeoninePretentiousPermutationEarring",
    },
    {
      firstName: "Ansel",
      lastName: "Mertz",
      job: {
        team: "architectures",
        title: "back-end",
        workplace: "Grimes - Heller",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FlubberPeonineJesterFruitySpecial",
    },
    {
      firstName: "Maria",
      lastName: "Sauer",
      job: {
        team: "interfaces",
        title: "front-end",
        workplace: "Hickle, Crist and Jacobson",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MitchianJesterEarring",
    },
    {
      firstName: "Stevie",
      lastName: "Robel",
      job: {
        team: "infrastructures",
        title: "world-class",
        workplace: "Schaefer LLC",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "ButterSalesmanMusicalCityFruity",
    },
    {
      firstName: "Jamal",
      lastName: "Rice",
      job: {
        team: "e-business",
        title: "visionary",
        workplace: "Jast, Jacobi and Gerhold",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "OathProfessorGreenPretentiousSpecial",
    },
    {
      firstName: "Jacinthe",
      lastName: "Crooks",
      job: {
        team: "deliverables",
        title: "proactive",
        workplace: "Strosin Inc",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "OathPuppyFruityGreenAbsurd",
    },
    {
      firstName: "Liam",
      lastName: "Duncan",
      job: {
        team: "Classroom",
        title: "Software Engineer and Mentor",
        workplace: "northcoders",
      },
      img_url:
        "https://cdn2.hubspot.net/hubfs/3489321/Photos/Staff%20Photos/Mitch_Sqaure.jpg",
      username: "Liam310",
    },
    {
      firstName: "Jewel",
      lastName: "Wiza",
      job: {
        team: "systems",
        title: "extensible",
        workplace: "Sporer, Reichel and Kautzer",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "PermutationPretentiousFruity",
    },
    {
      firstName: "Sarah",
      lastName: "Browncross",
      job: {
        workplace: "northcoders",
        team: "Apprenticeships",
        title: "Solutions Manager",
      },
      img_url:
        "https://images.prismic.io/northcoders/859a994e-ad5d-43c5-b99e-73989253e20f_Sarah+Browncross+Headshot+24-05-21.jpg?auto=compress%2Cformat&rect=0%2C0%2C3434%2C3434&w=800&fit=max&q=60",
      username: "SarahBrowncross",
    },
    {
      firstName: "Mark",
      lastName: "Terry",
      job: {
        team: "eyeballs",
        title: "strategic",
        workplace: "Gleichner and Sons",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FruityJesterShadesMoose",
    },
    {
      firstName: "Douglas",
      lastName: "Bayer",
      job: {
        team: "solutions",
        title: "efficient",
        workplace: "Ruecker - Schroeder",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "SpecialMitchianGreen",
    },
    {
      firstName: "Frederik",
      lastName: "Tremblay",
      job: {
        team: "interfaces",
        title: "user-centric",
        workplace: "Dach - Treutel",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "EarringDangerousRubyJesterPeonine",
    },
    {
      firstName: "Shanon",
      lastName: "Schultz",
      job: {
        team: "methodologies",
        title: "value-added",
        workplace: "Beatty, Nicolas and Jakubowski",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "EarnestPuppyPraline",
    },
    {
      firstName: "Sigmund",
      lastName: "Bradtke",
      job: {
        team: "markets",
        title: "24/7",
        workplace: "Morissette - Barrows",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FriendlyButterCircularMitchian",
    },
    {
      firstName: "Ant",
      lastName: "Medina",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Mentor",
      },
      img_url:
        "https://images.prismic.io/northcoders/da9de623-e356-435a-92d6-421966a17898_ant-coding-bootcamp-tutor.jpg?auto=compress%2Cformat&rect=21%2C13%2C206%2C206&w=800&fit=max&q=60",
      username: "AnthonyMedina",
    },
    {
      firstName: "Aileen",
      lastName: "Harris",
      job: {
        team: "e-services",
        title: "transparent",
        workplace: "VonRueden, Streich and Jacobson",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "PermutationEarringMonster",
    },
    {
      firstName: "Paul",
      lastName: "Copley",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Mentor",
      },
      img_url:
        "https://images.prismic.io/northcoders/bbbb23b9-a160-4726-8dec-57b17d6de8da_Paul+Copley.jpg?auto=compress%2Cformat&rect=762%2C410%2C2139%2C2139&w=800&fit=max&q=60",
      username: "P-Copley",
    },
    {
      firstName: "Alayna",
      lastName: "Feest",
      job: {
        team: "experiences",
        title: "cross-platform",
        workplace: "Armstrong Inc",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "EarringNuttyAbsurd",
    },
    {
      firstName: "Else",
      lastName: "Kub",
      job: { team: "architectures", title: "global", workplace: "Bartell Inc" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "JesterPralineEarnestAbsurdSpecial",
    },
    {
      firstName: "Caesar",
      lastName: "Kunze",
      job: {
        team: "web services",
        title: "real-time",
        workplace: "Nolan and Sons",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "JesterSalesmanPretentious",
    },
    {
      firstName: "Susie",
      lastName: "Brown",
      job: {
        team: "applications",
        title: "best-of-breed",
        workplace: "Wintheiser LLC",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FishfingerNuttyButter",
    },
    {
      firstName: "Petra",
      lastName: "Johnson",
      job: {
        team: "schemas",
        title: "dot-com",
        workplace: "Bashirian and Sons",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "ButterVikingSpecial",
    },
    {
      firstName: "Alden",
      lastName: "Harris",
      job: {
        team: "e-markets",
        title: "real-time",
        workplace: "Barton and Sons",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MitchianLeemaFriendlyViking",
    },
    {
      firstName: "Adonis",
      lastName: "Willms",
      job: {
        team: "partnerships",
        title: "distributed",
        workplace: "Bechtelar Group",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "LeemaFishfingerShades",
    },
    {
      firstName: "Vada",
      lastName: "Reynolds",
      job: {
        team: "mindshare",
        title: "cross-platform",
        workplace: "Heathcote, Hartmann and Satterfield",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MusicalConsolidateRubyMoose",
    },
    {
      firstName: "Marcos",
      lastName: "Romaguera",
      job: {
        team: "applications",
        title: "out-of-the-box",
        workplace: "Heaney - Schinner",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FriendlyMooseFlubberViking",
    },
    {
      firstName: "Hadley",
      lastName: "Donnelly",
      job: {
        team: "channels",
        title: "bricks-and-clicks",
        workplace: "Harris, Harvey and Jenkins",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MonsterPralineGreen",
    },
    {
      firstName: "Flavio",
      lastName: "Batz",
      job: {
        team: "synergies",
        title: "granular",
        workplace: "Keebler, Lind and Johns",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "ConsolidateLeemaViking",
    },
    {
      firstName: "Kirk",
      lastName: "Lakin",
      job: {
        team: "eyeballs",
        title: "robust",
        workplace: "Hayes, Lebsack and Mosciski",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "PuppyLeemaProfessorEarring",
    },
    {
      firstName: "Izaiah",
      lastName: "Ortiz",
      job: { team: "bandwidth", title: "magnetic", workplace: "Purdy - Haley" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "CitySpecialRubyLeemaPermutation",
    },
    {
      firstName: "Jeremy",
      lastName: "Kuvalis",
      job: {
        team: "initiatives",
        title: "vertical",
        workplace: "McClure - Parker",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "OathFlubberPeonine",
    },
    {
      firstName: "Price",
      lastName: "Murray",
      job: {
        team: "applications",
        title: "user-centric",
        workplace: "Zieme and Sons",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FruityCircularAbsurdFriendlyEarnest",
    },
    {
      firstName: "Francesco",
      lastName: "Luettgen",
      job: { team: "models", title: "ubiquitous", workplace: "Green and Sons" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "ProfessorMooseFlubberMitchian",
    },
    {
      firstName: "Lawson",
      lastName: "Cummings",
      job: { team: "portals", title: "global", workplace: "Hudson - Johns" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "PralineFishfingerPeonineCityLeema",
    },
    {
      firstName: "Vaughn",
      lastName: "Satterfield",
      job: {
        team: "markets",
        title: "one-to-one",
        workplace: "Marvin, Nicolas and Franecki",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "ConsolidateLeemaSpecialVikingEarnest",
    },
    {
      firstName: "Amiya",
      lastName: "Borer",
      job: {
        team: "platforms",
        title: "holistic",
        workplace: "Brakus, Gutkowski and Renner",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MooseProfessorJesterCircular",
    },
    {
      firstName: "Erna",
      lastName: "Thiel",
      job: { team: "vortals", title: "virtual", workplace: "Turner Group" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MoosePralineViking",
    },
    {
      firstName: "Vidal",
      lastName: "Little",
      job: {
        team: "portals",
        title: "extensible",
        workplace: "O'Kon - Carter",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "JesterRubyDangerousLeemaEarring",
    },
    {
      firstName: "Ruth",
      lastName: "Ng",
      job: {
        workplace: "northcoders",
        team: "Apprenticeships",
        title: "Chief Operating Officer - Apprenticeships",
      },
      img_url:
        "https://info.northcoders.com/hubfs/Photos/Staff%20Photos/Ruth_Sqaure.jpg",
      username: "RuthYMNg",
    },
    {
      firstName: "Bryana",
      lastName: "Beier",
      job: {
        team: "metrics",
        title: "impactful",
        workplace: "Weimann, Hermann and Parker",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MonsterLeemaProfessor",
    },
    {
      firstName: "Sam",
      lastName: "Caine",
      job: {
        workplace: "northcoders",
        team: "Solutions",
        title: "Head of Engineering",
      },
      img_url:
        "https://images.prismic.io/northcoders/415220a7-9808-43de-ba0d-898f7d414a53_Sam+Headshot+May+2021.jpg?auto=compress%2Cformat&rect=0%2C0%2C3404%2C3404&w=800&fit=max&q=60",
      username: "icellusedkars",
    },
    {
      firstName: "Lucy",
      lastName: "Galway",
      job: {
        workplace: "northcoders",
        team: "Partnerships",
        title: "Success Manager",
      },
      img_url:
        "https://images.prismic.io/northcoders/1304b8c6-4d6c-4559-a9c7-d2b7a48fc80b_Lucy+Headshot.jpg?auto=compress%2Cformat&rect=0%2C0%2C3434%2C3434&w=800&fit=max&q=60",
      username: "lucy_g",
    },
    {
      firstName: "Berta",
      lastName: "Steuber",
      job: {
        team: "e-services",
        title: "leading-edge",
        workplace: "Marvin LLC",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "RubyNuttyAbsurdEarringEarnest",
    },
    {
      firstName: "Kyleigh",
      lastName: "Schaden",
      job: {
        team: "initiatives",
        title: "customized",
        workplace: "Schiller LLC",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FishfingerDangerousShadesButter",
    },
    {
      firstName: "Vel",
      lastName: "Georgieva",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Head of Mentoring",
      },
      img_url:
        "https://images.prismic.io/northcoders/c5edd30a-1949-4e62-87b8-7e45313542bb_Vel.jpg?auto=compress%2Cformat&rect=1236%2C376%2C1755%2C1755&w=800&fit=max&q=60",
      username: "antariess",
    },
    {
      firstName: "Carol",
      lastName: "Kris",
      job: { team: "supply-chains", title: "vertical", workplace: "Beer LLC" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FlubberFishfingerCityEarringPermutation",
    },
    {
      firstName: "Paul",
      lastName: "Rogerson",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Head of Mentoring",
      },
      img_url:
        "https://images.prismic.io/northcoders/5ffa1ae0-0e83-47aa-a5f2-d4b6ef24af5a_Paul+R.jpg?auto=compress%2Cformat&rect=541%2C62%2C2596%2C2596&w=800&fit=max&q=60",
      username: "rogersop",
    },
    {
      firstName: "Haz",
      lastName: "Mallion",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Mentor",
      },
      img_url:
        "https://images.prismic.io/northcoders/6afa9655-74e8-4d6b-aa82-449576a65515_Haz.png?auto=compress%2Cformat&rect=181%2C161%2C1203%2C1203&w=800&fit=max&q=60",
      username: "mallionaire",
    },
    {
      firstName: "Cory",
      lastName: "Ondricka",
      job: {
        team: "metrics",
        title: "rich",
        workplace: "Kub, Bayer and Hammes",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "CityVikingPermutationSalesman",
    },
    {
      firstName: "Jerald",
      lastName: "Hegmann",
      job: { team: "e-markets", title: "dot-com", workplace: "Abbott Group" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "EarnestShadesFruityOathRuby",
    },
    {
      firstName: "Amy",
      lastName: "Wild",
      job: {
        workplace: "northcoders",
        team: "General",
        title: "Chief Commerical Officer",
      },
      img_url:
        "https://images.prismic.io/northcoders/467897a9-dccc-4c65-846d-c4d08a7f3798_amy-wild-cco-northcoders.jpg?auto=compress%2Cformat&rect=0%2C0%2C400%2C400&w=800&fit=max&q=60",
      username: "amy_wild",
    },
    {
      firstName: "Sonny",
      lastName: "Hane",
      job: { team: "vortals", title: "real-time", workplace: "Schmeler Group" },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MitchianMusicalPralineCity",
    },
    {
      firstName: "Kris",
      lastName: "Mosciski",
      job: {
        team: "convergence",
        title: "user-centric",
        workplace: "Nolan Group",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "CitySalesmanEarnestCircular",
    },
    {
      firstName: "Jaime",
      lastName: "Hilll",
      job: {
        team: "bandwidth",
        title: "magnetic",
        workplace: "Lindgren Group",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "LeemaRubyCircularMonster",
    },
    {
      firstName: "Xander",
      lastName: "Wintheiser",
      job: {
        team: "interfaces",
        title: "back-end",
        workplace: "Balistreri Inc",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "OathFlubberGreenSalesmanPraline",
    },
    {
      firstName: "David",
      lastName: "Bartlett",
      job: {
        workplace: "northcoders",
        team: "Classroom",
        title: "Software Engineer and Mentor",
      },
      img_url:
        "https://images.prismic.io/northcoders/254ea17a-4e92-4b33-843d-c749fc9215b7_David+Headshot+May+2021.jpg?auto=compress%2Cformat&rect=0%2C0%2C3600%2C3600&w=800&fit=max&q=60",
      username: "daviidbartlett",
    },
    {
      firstName: "Claire",
      lastName: "Feil",
      job: {
        team: "action-items",
        title: "B2B",
        workplace: "Breitenberg, Schimmel and Cummings",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "NuttyFruityVikingShadesOath",
    },
    {
      firstName: "Jeffery",
      lastName: "Lubowitz",
      job: {
        team: "functionalities",
        title: "extensible",
        workplace: "Littel - Turner",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "FishfingerOathPretentiousMusical",
    },
    {
      firstName: "Hank",
      lastName: "Skiles",
      job: {
        team: "e-tailers",
        title: "viral",
        workplace: "Trantow - Kerluke",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "MoosePuppySalesmanGreen",
    },
    {
      firstName: "Issac",
      lastName: "Smith",
      job: {
        team: "content",
        title: "efficient",
        workplace: "Feil, Funk and Brown",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "AbsurdRubyPretentiousPeonine",
    },
    {
      firstName: "Lori",
      lastName: "Williamson",
      job: {
        team: "partnerships",
        title: "plug-and-play",
        workplace: "Boehm - Roob",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "NuttyVikingConsolidate",
    },
    {
      firstName: "Shyann",
      lastName: "Emard",
      job: {
        team: "bandwidth",
        title: "interactive",
        workplace: "Keebler - Streich",
      },
      img_url: "http://lorempixel.com/640/480/people",
      username: "CircularPralinePeonineNutty",
    },
  ],
};
